{["loot_id"] = "21837", ["loot_name"] = "Anubisath Warhammer", ["prio"] = " Prio: Wurm(9) > Maddi(12) > Hamma (5) > Nirenah > Kruzade > "},
{["loot_id"] = "21836", ["loot_name"] = "Ritssyn's Ring of Chaos ", ["prio"] = " Prio: Greun > Hankmoody > Talatro > Kendy > "},
{["loot_id"] = "21891", ["loot_name"] = "Shard of the Fallen Star ", ["prio"] = " Prio: "},
{["loot_id"] = "20928", ["loot_name"] = "Qiraji Bindings of Command", ["prio"] = " Prio: Exc > Wurm(19)  > Exc > "},
{["loot_id"] = "20932", ["loot_name"] = "Qiraji Bindings of Dominance", ["prio"] = " Prio: "},
{["loot_id"] = "20930", ["loot_name"] = "Vek'lor's Diadem", ["prio"] = " Prio: Exc > "},
{["loot_id"] = "20926", ["loot_name"] = "Vek'nilash's Circlet", ["prio"] = " Prio: Exc > "},
{["loot_id"] = "20927", ["loot_name"] = "Ouro's Intact Hide", ["prio"] = " Prio: Vulkania > Exc > "},
{["loot_id"] = "20931", ["loot_name"] = "Skin of the Great Sandworm", ["prio"] = " Prio: "},
{["loot_id"] = "20929", ["loot_name"] = "Carapace of the old God", ["prio"] = " Prio: Exc > "},
{["loot_id"] = "20933", ["loot_name"] = "Husk of the Old God", ["prio"] = " Prio: "},
{["loot_id"] = "21232", ["loot_name"] = "Imperial Qiraji Armaments", ["prio"] = " Prio: Exc > Hamma (3) > "},
{["loot_id"] = "21237", ["loot_name"] = "Imperial Qiraji Regalia", ["prio"] = " Prio: Hayze > Nirenah > Wurm(20) > Ilarion > "},
{["loot_id"] = "21128", ["loot_name"] = "Staff of the Qiraji Prophets", ["prio"] = " Prio: Starbuzz > Kendy > "},
{["loot_id"] = "21707", ["loot_name"] = "Ring of Swarming Thought", ["prio"] = " Prio: "},
{["loot_id"] = "21814", ["loot_name"] = "Breastplate of Annihilation", ["prio"] = " Prio: Ragnoz > Nirenah > Kruzade > Hayze > "},
{["loot_id"] = "21701", ["loot_name"] = "Cloak of Concentrated Hatred", ["prio"] = " Prio: Alvaroh (?) > Ninjawodja > Exc > VodkaO (9) > Ragnoz > "},
{["loot_id"] = "21688", ["loot_name"] = "Boots of the Fallen Hero", ["prio"] = " Prio: "},
{["loot_id"] = "21690", ["loot_name"] = "Angelista's Charm", ["prio"] = " Prio: Palas (falls Interesse) wüfeln > "},
{["loot_id"] = "21686", ["loot_name"] = "Mantle of Phrenic Power", ["prio"] = " Prio: "},
{["loot_id"] = "21693", ["loot_name"] = "Guise of the Devourer", ["prio"] = " Prio: Ronerva > "},
{["loot_id"] = "21680", ["loot_name"] = "Vest of Swift Execution", ["prio"] = " Prio: Møøn > "},
{["loot_id"] = "21603", ["loot_name"] = "Wand of Qiraji Nobility", ["prio"] = " Prio: Ester > Vulkania > Greun > Cz > Talatro > "},
{["loot_id"] = "21694", ["loot_name"] = "Ternary Mantle", ["prio"] = " Prio: Enymen > "},
{["loot_id"] = "21695", ["loot_name"] = "Angelista's Touch", ["prio"] = " Prio: "},
{["loot_id"] = "21666", ["loot_name"] = "Sartura's Might", ["prio"] = " Prio: Tororin > If > Elfierde > Pvpgott = Anyph = Para = Enymen =  Methy > Moon > "},
{["loot_id"] = "21667", ["loot_name"] = "Legplates of Blazing Light", ["prio"] = " Prio: Perseas > "},
{["loot_id"] = "21669", ["loot_name"] = "Creeping Vine Helm", ["prio"] = " Prio: Pvpgott > "},
{["loot_id"] = "21670", ["loot_name"] = "Badge of the Swarmguard", ["prio"] = " Prio: Flüffel > Wurm(7) > Seyt(8) > Maddi(10) > Hamma (13) > "},
{["loot_id"] = "21672", ["loot_name"] = "Gloves of Enforcement", ["prio"] = " Prio: Ailenya (11) > Møøn > (Krieger ohne ctun Hände) > Exe > VodkaO (5) > "},
{["loot_id"] = "21671", ["loot_name"] = "Robes of the Battleguard", ["prio"] = " Prio: "},
{["loot_id"] = "21673", ["loot_name"] = "Silithid Claw", ["prio"] = " Prio: Flüffel (5) > Elyriel (5) > "},
{["loot_id"] = "21674", ["loot_name"] = "Gauntlets of Steadfast Determination", ["prio"] = " Prio: Kruzade > "},
{["loot_id"] = "21676", ["loot_name"] = "Leggings of the Festering Swarm", ["prio"] = " Prio: Kendy > Vulkania > "},
{["loot_id"] = "21650", ["loot_name"] = "Ancient Qiraji Ripper", ["prio"] = " Prio: Ragnoz > Nirenah > Ailenya (4) > Alvaroh (15) > Hamma (20) > "},
{["loot_id"] = "21663", ["loot_name"] = "Robes of the Guardian Saint", ["prio"] = " Prio: Anyph > If > Pvpgott > Para > Methy > "},
{["loot_id"] = "21664", ["loot_name"] = "Barbed Choker", ["prio"] = " Prio: Ragefire > Thranng(8) > Nirenah > Ragnoz > Kruzade > "},
{["loot_id"] = "21651", ["loot_name"] = "Scaled Sand Reaver Leggings", ["prio"] = " Prio: "},
{["loot_id"] = "21622", ["loot_name"] = "Sharpened Silithid Femur", ["prio"] = " Prio: Nitilas > Starbuzz > Cz > Greun > Talatro > "},
{["loot_id"] = "21625", ["loot_name"] = "Scarab Brooch", ["prio"] = " Prio: Methy > Toro > Pala3 > If > Ronerva > "},
{["loot_id"] = "21677", ["loot_name"] = "Ring of the Qiraji Fury", ["prio"] = " Prio: Seyt(1) > Wurm(5) > Ragefire(7) > Maddi(6) > Baldemar (3) > "},
{["loot_id"] = "22399", ["loot_name"] = "Idol of Health", ["prio"] = " Prio: Pvpgott > "},
{["loot_id"] = "21617", ["loot_name"] = "Wasphide Gauntlets", ["prio"] = " Prio: Pvpgott > "},
{["loot_id"] = "21618", ["loot_name"] = "Hive Defiler Wristguards", ["prio"] = " Prio: Wurm(4) > Nirenah > Ragnoz > Thranng(6) > Hayze > "},
{["loot_id"] = "21619", ["loot_name"] = "Gloves of the Messiah", ["prio"] = " Prio: Enymen > "},
{["loot_id"] = "21620", ["loot_name"] = "Ring of the Martyr", ["prio"] = " Prio: Pvpgott > Tororin > Methy > Elfierde > Anyph > "},
{["loot_id"] = "21621", ["loot_name"] = "Cloak of the Golden Hive", ["prio"] = " Prio: "},
{["loot_id"] = "21598", ["loot_name"] = "Royal Qiraji Belt", ["prio"] = " Prio: Kruzade > Hayze > "},
{["loot_id"] = "21597", ["loot_name"] = "Royal Scepter of Vek'lor", ["prio"] = " Prio: Cz > Starbuzz > Greun > Talatro > Phizzy > "},
{["loot_id"] = "21600", ["loot_name"] = "Boots of Epiphany", ["prio"] = " Prio: Methy > "},
{["loot_id"] = "21602", ["loot_name"] = "Qiraji Execution Bracers", ["prio"] = " Prio: Ronerva > Møøn > Hamma (14) > Exc > VodkaO (?) > "},
{["loot_id"] = "21604", ["loot_name"] = "Bracelets of Royal Redemption ", ["prio"] = " Prio: Methy > Pvpgott > Para > Toro > Ronerva > "},
{["loot_id"] = "21608", ["loot_name"] = "Amulet of Vek'nilash", ["prio"] = " Prio: Hankmoody > Greun > Nitilas > Cz > Kendy > "},
{["loot_id"] = "21609", ["loot_name"] = "Regenerating Belt of Vek'nilash", ["prio"] = " Prio: Pvpgott > If > "},
{["loot_id"] = "21610", ["loot_name"] = "Wormscale Blocker", ["prio"] = " Prio: Anyph > "},
{["loot_id"] = "21615", ["loot_name"] = "Don Rigoberto's Lost Hat", ["prio"] = " Prio: Enymen > Blargus > Toro > If > Methy > "},
{["loot_id"] = "23557", ["loot_name"] = "Larvae of the Great Worm", ["prio"] = " Prio: Seyt(4) > Thranng (9) > Cammy (11) > Hamma (12) > Alvaroh (?) > "},
{["loot_id"] = "23570", ["loot_name"] = "Jom Gabbar", ["prio"] = " Prio: Alvaroh (3) > Ailenya (3) > Cammy (4) > Seyt(7) > Nirenah > "},
{["loot_id"] = "21221", ["loot_name"] = "Eye of C'thun", ["prio"] = " Prio: If > Kruzade > Hayze > Hamma (11) > Cammy (14) > "},
{["loot_id"] = "21126", ["loot_name"] = "Death's Sting", ["prio"] = " Prio: Ninja > Exc >  VodkaO (4) > Hamma (20) > Cammy (20) > "},
{["loot_id"] = "21134", ["loot_name"] = "Dark Edge of Insanity", ["prio"] = " Prio: Seyt(9) > Thranng (8) > Ragnoz > "},
{["loot_id"] = "21581", ["loot_name"] = "Gauntlets of Annihilation", ["prio"] = " Prio: Ragnoz > Nirenah > Kruzade > Hayze > "},
{["loot_id"] = "21582", ["loot_name"] = "Grasp of the Old God", ["prio"] = " Prio: Anyph > If > Ilarion > Elfierde > Pvpgott > "},
{["loot_id"] = "21583", ["loot_name"] = "Cloak of Clarity", ["prio"] = " Prio: Pvpgott > Anyph > If = Para > Methy > Enymen > "},
{["loot_id"] = "21585", ["loot_name"] = "Dark Storm Gauntlets", ["prio"] = " Prio: Starbuzz > Talatro > Nitilas > Phizzy > Greun > "},
{["loot_id"] = "21586", ["loot_name"] = "Belt of Never-ending Agony", ["prio"] = " Prio: Cammy (3) > Ailenya (5) > Ronerva > Exc > VodkaO (3) > "},
{["loot_id"] = "21596", ["loot_name"] = "Ring of the Godslayer", ["prio"] = " Prio: Wurm > Maddi > "},
{["loot_id"] = "21839", ["loot_name"] = "Scepter of the False Prophet", ["prio"] = " Prio: Elfierde > Para > Anyph > Methy > Tororin > "},
{["loot_id"] = "22730", ["loot_name"] = "Eyestalk Waist Cord", ["prio"] = " Prio: Cz > Talatro > Starbuzz > Ester > Nitilas > "},
{["loot_id"] = "22731", ["loot_name"] = "Cloak of the Devoured", ["prio"] = " Prio: Greun > Starbuzz > Nitilas > Kendy > Talatro > "},
{["loot_id"] = "22732", ["loot_name"] = "Mark of C'Thun", ["prio"] = " Prio: Ragnoz > Nirenah > Maddi > Wurm > "},
{["loot_id"] = "23667", ["loot_name"] = "Spaulders of the Grand Crusader", ["prio"] = " Prio: "},
{["loot_id"] = "23069", ["loot_name"] = "Necro-Knight's Garb", ["prio"] = " Prio: "},
{["loot_id"] = "23226", ["loot_name"] = "Ghoul Skin Tunic", ["prio"] = " Prio: "},
{["loot_id"] = "23663", ["loot_name"] = "Girdle of Elemental Fury", ["prio"] = " Prio: "},
{["loot_id"] = "23666", ["loot_name"] = "Belt of the Grand Crusader", ["prio"] = " Prio: "},
{["loot_id"] = "23668", ["loot_name"] = "Leggings of the Grand Crusader", ["prio"] = " Prio: "},
{["loot_id"] = "23237", ["loot_name"] = "Ring of the Eternal Flame", ["prio"] = " Prio: "},
{["loot_id"] = "23238", ["loot_name"] = "Stygian Buckler", ["prio"] = " Prio: "},
{["loot_id"] = "23044", ["loot_name"] = "Harbinger of Doom", ["prio"] = " Prio: "},
{["loot_id"] = "23221", ["loot_name"] = "Misplaced Servo Arm", ["prio"] = " Prio: "},
{["loot_id"] = "22369", ["loot_name"] = "Desecrated Bindings", ["prio"] = " Prio: "},
{["loot_id"] = "22362", ["loot_name"] = "Desecrated Wristguards", ["prio"] = " Prio: "},
{["loot_id"] = "22355", ["loot_name"] = "Desecrated Bracers", ["prio"] = " Prio: "},
{["loot_id"] = "22371", ["loot_name"] = "Desecrated Gloves", ["prio"] = " Prio: "},
{["loot_id"] = "22364", ["loot_name"] = "Desecrated Handguards", ["prio"] = " Prio: "},
{["loot_id"] = "22357", ["loot_name"] = "Desecrated Gauntlets", ["prio"] = " Prio: "},
{["loot_id"] = "22368", ["loot_name"] = "Desecrated Shoulderpads", ["prio"] = " Prio: "},
{["loot_id"] = "22361", ["loot_name"] = "Desecrated Spaulders", ["prio"] = " Prio: "},
{["loot_id"] = "22354", ["loot_name"] = "Desecrated Pauldrons", ["prio"] = " Prio: "},
{["loot_id"] = "22367", ["loot_name"] = "Desecrated Circlet", ["prio"] = " Prio: "},
{["loot_id"] = "22360", ["loot_name"] = "Desecrated Headpiece", ["prio"] = " Prio: "},
{["loot_id"] = "22353", ["loot_name"] = "Desecrated Helmet", ["prio"] = " Prio: "},
{["loot_id"] = "22370", ["loot_name"] = "Desecrated Belt", ["prio"] = " Prio: "},
{["loot_id"] = "22363", ["loot_name"] = "Desecrated Girdle", ["prio"] = " Prio: "},
{["loot_id"] = "22356", ["loot_name"] = "Desecrated Waistguard", ["prio"] = " Prio: "},
{["loot_id"] = "22366", ["loot_name"] = "Desecrated Leggings", ["prio"] = " Prio: "},
{["loot_id"] = "22359", ["loot_name"] = "Desecrated Legguards", ["prio"] = " Prio: "},
{["loot_id"] = "22352", ["loot_name"] = "Desecrated Legplates", ["prio"] = " Prio: "},
{["loot_id"] = "22372", ["loot_name"] = "Desecrated Sandals", ["prio"] = " Prio: "},
{["loot_id"] = "22365", ["loot_name"] = "Desecrated Boots", ["prio"] = " Prio: "},
{["loot_id"] = "22358", ["loot_name"] = "Desecrated Sabatons", ["prio"] = " Prio: "},
{["loot_id"] = "22351", ["loot_name"] = "Desecrated Robe", ["prio"] = " Prio: "},
{["loot_id"] = "22350", ["loot_name"] = "Desecrated Tunic", ["prio"] = " Prio: "},
{["loot_id"] = "22349", ["loot_name"] = "Desecrated Breastplate", ["prio"] = " Prio: "},
{["loot_id"] = "22935", ["loot_name"] = "Touch of Frost", ["prio"] = " Prio: "},
{["loot_id"] = "22938", ["loot_name"] = "Cryptfiend Silk Cloak", ["prio"] = " Prio: "},
{["loot_id"] = "22936", ["loot_name"] = "Wristguards of Vengeance", ["prio"] = " Prio: "},
{["loot_id"] = "22939", ["loot_name"] = "Band of Unanswered Prayers", ["prio"] = " Prio: "},
{["loot_id"] = "22937", ["loot_name"] = "Gem of Nerubis", ["prio"] = " Prio: "},
{["loot_id"] = "22943", ["loot_name"] = "Malice Stone Pendant", ["prio"] = " Prio: "},
{["loot_id"] = "22941", ["loot_name"] = "Polar Shoulder Pads", ["prio"] = " Prio: "},
{["loot_id"] = "22940", ["loot_name"] = "Icebane Pauldrons", ["prio"] = " Prio: "},
{["loot_id"] = "22942", ["loot_name"] = "The Widow's Embrace", ["prio"] = " Prio: "},
{["loot_id"] = "22806", ["loot_name"] = "Widow's Remorse", ["prio"] = " Prio: "},
{["loot_id"] = "22947", ["loot_name"] = "Pendant of Forgotten Names", ["prio"] = " Prio: "},
{["loot_id"] = "23220", ["loot_name"] = "Crystal Webbed Robe", ["prio"] = " Prio: "},
{["loot_id"] = "22954", ["loot_name"] = "Kiss of the Spider", ["prio"] = " Prio: "},
{["loot_id"] = "22807", ["loot_name"] = "Wraith Blade", ["prio"] = " Prio: "},
{["loot_id"] = "22804", ["loot_name"] = "Maexxna's Fang", ["prio"] = " Prio: "},
{["loot_id"] = "22960", ["loot_name"] = "Cloak of Suturing", ["prio"] = " Prio: "},
{["loot_id"] = "22961", ["loot_name"] = "Band of Reanimation ", ["prio"] = " Prio: "},
{["loot_id"] = "22820", ["loot_name"] = "Wand of Fates", ["prio"] = " Prio: "},
{["loot_id"] = "22818", ["loot_name"] = "The Plague Bearer", ["prio"] = " Prio: "},
{["loot_id"] = "22815", ["loot_name"] = "Severance", ["prio"] = " Prio: "},
{["loot_id"] = "22968", ["loot_name"] = "Glacial Mantle", ["prio"] = " Prio: "},
{["loot_id"] = "22967", ["loot_name"] = "Icy Scale Spaulders", ["prio"] = " Prio: "},
{["loot_id"] = "22810", ["loot_name"] = "Toxin Injector", ["prio"] = " Prio: "},
{["loot_id"] = "22803", ["loot_name"] = "Midnight Haze", ["prio"] = " Prio: "},
{["loot_id"] = "22988", ["loot_name"] = "The End of Dreams", ["prio"] = " Prio: "},
{["loot_id"] = "22983", ["loot_name"] = "Rime Covered Mantle", ["prio"] = " Prio: "},
{["loot_id"] = "22981", ["loot_name"] = "Gluth's Missing Collar", ["prio"] = " Prio: "},
{["loot_id"] = "22994", ["loot_name"] = "Digested Hand of Power", ["prio"] = " Prio: "},
{["loot_id"] = "23075", ["loot_name"] = "Death's Bargain", ["prio"] = " Prio: "},
{["loot_id"] = "22813", ["loot_name"] = "Claymore of Unholy Might", ["prio"] = " Prio: "},
{["loot_id"] = "23000", ["loot_name"] = "Plated Abomination Ribcage", ["prio"] = " Prio: "},
{["loot_id"] = "23070", ["loot_name"] = "Leggings of Polarity", ["prio"] = " Prio: "},
{["loot_id"] = "23001", ["loot_name"] = "Eye of Diminution", ["prio"] = " Prio: "},
{["loot_id"] = "22808", ["loot_name"] = "The Castigator", ["prio"] = " Prio: "},
{["loot_id"] = "22801", ["loot_name"] = "Spire of Twilight", ["prio"] = " Prio: "},
{["loot_id"] = "23030", ["loot_name"] = "Cloak of the Scourge", ["prio"] = " Prio: "},
{["loot_id"] = "23031", ["loot_name"] = "Band of the Inevitable", ["prio"] = " Prio: "},
{["loot_id"] = "23028", ["loot_name"] = "Hailstone Band", ["prio"] = " Prio: "},
{["loot_id"] = "23029", ["loot_name"] = "Noth's Frigid Heart", ["prio"] = " Prio: "},
{["loot_id"] = "23006", ["loot_name"] = "Libram of Light", ["prio"] = " Prio: "},
{["loot_id"] = "22816", ["loot_name"] = "Hatchet of Sundered Bone", ["prio"] = " Prio: "},
{["loot_id"] = "23035", ["loot_name"] = "Preceptor's Hat", ["prio"] = " Prio: "},
{["loot_id"] = "23033", ["loot_name"] = "Icy Scale Coif", ["prio"] = " Prio: "},
{["loot_id"] = "23019", ["loot_name"] = "Icebane Helmet", ["prio"] = " Prio: "},
{["loot_id"] = "23036", ["loot_name"] = "Necklace of Necropsy", ["prio"] = " Prio: "},
{["loot_id"] = "23068", ["loot_name"] = "Legplates of Carnage", ["prio"] = " Prio: "},
{["loot_id"] = "23038", ["loot_name"] = "Band of Unnatural Forces", ["prio"] = " Prio: "},
{["loot_id"] = "23037", ["loot_name"] = "Ring of Spiritual Fervor", ["prio"] = " Prio: "},
{["loot_id"] = "23042", ["loot_name"] = "Loatheb's Reflection", ["prio"] = " Prio: "},
{["loot_id"] = "23039", ["loot_name"] = "The Eye of Nerub", ["prio"] = " Prio: "},
{["loot_id"] = "22800", ["loot_name"] = "Brimstone Staff", ["prio"] = " Prio: "},
{["loot_id"] = "23017", ["loot_name"] = "Veil of Eclipse", ["prio"] = " Prio: "},
{["loot_id"] = "23219", ["loot_name"] = "Girdle of the Mentor", ["prio"] = " Prio: "},
{["loot_id"] = "23018", ["loot_name"] = "Signet of the Fallen Defender", ["prio"] = " Prio: "},
{["loot_id"] = "23004", ["loot_name"] = "Idol of Longevity", ["prio"] = " Prio: "},
{["loot_id"] = "23009", ["loot_name"] = "Wand of the Whispering Dead", ["prio"] = " Prio: "},
{["loot_id"] = "23014", ["loot_name"] = "Iblis, Blade of the Fallen Seraph", ["prio"] = " Prio: "},
{["loot_id"] = "23032", ["loot_name"] = "Glacial Headdress", ["prio"] = " Prio: "},
{["loot_id"] = "23020", ["loot_name"] = "Polar Helmet", ["prio"] = " Prio: "},
{["loot_id"] = "23023", ["loot_name"] = "Sadist's Collar", ["prio"] = " Prio: "},
{["loot_id"] = "23021", ["loot_name"] = "The Soul Harvester's Bindings", ["prio"] = " Prio: "},
{["loot_id"] = "23073", ["loot_name"] = "Boots of Displacement", ["prio"] = " Prio: "},
{["loot_id"] = "23071", ["loot_name"] = "Leggings of Apocalypse", ["prio"] = " Prio: "},
{["loot_id"] = "23025", ["loot_name"] = "Seal of the Damned", ["prio"] = " Prio: "},
{["loot_id"] = "23027", ["loot_name"] = "Warmth of Forgiveness", ["prio"] = " Prio: "},
{["loot_id"] = "22811", ["loot_name"] = "Soulstring", ["prio"] = " Prio: "},
{["loot_id"] = "22809", ["loot_name"] = "Maul of the Redeemed Crusader", ["prio"] = " Prio: "},
{["loot_id"] = "22691", ["loot_name"] = "Corrupted Ashbringer", ["prio"] = " Prio: "},
{["loot_id"] = "23548", ["loot_name"] = "Might of the Scourge", ["prio"] = " Prio: "},
{["loot_id"] = "23545", ["loot_name"] = "Power of the Scourge", ["prio"] = " Prio: "},
{["loot_id"] = "23050", ["loot_name"] = "Cloak of the Necropolis", ["prio"] = " Prio: "},
{["loot_id"] = "23045", ["loot_name"] = "Shroud of Dominion", ["prio"] = " Prio: "},
{["loot_id"] = "23040", ["loot_name"] = "Glyph of Deflection", ["prio"] = " Prio: "},
{["loot_id"] = "23047", ["loot_name"] = "Eye of the Dead", ["prio"] = " Prio: "},
{["loot_id"] = "23041", ["loot_name"] = "Slayer's Crest", ["prio"] = " Prio: "},
{["loot_id"] = "23046", ["loot_name"] = "The Restrained Essence of Sapphiron", ["prio"] = " Prio: "},
{["loot_id"] = "23049", ["loot_name"] = "Sapphiron's Left Eye", ["prio"] = " Prio: "},
{["loot_id"] = "23048", ["loot_name"] = "Sapphiron's Right Eye", ["prio"] = " Prio: "},
{["loot_id"] = "23043", ["loot_name"] = "The Face of Death", ["prio"] = " Prio: "},
{["loot_id"] = "23242", ["loot_name"] = "Claw of the Frost Wyrm", ["prio"] = " Prio: "},
{["loot_id"] = "22520", ["loot_name"] = "The Phylactery of Kel'Thuzad", ["prio"] = " Prio: "},
{["loot_id"] = "23057", ["loot_name"] = "Gem of Trapped Innocents", ["prio"] = " Prio: "},
{["loot_id"] = "23053", ["loot_name"] = "Stormrage's Talisman of Seething", ["prio"] = " Prio: "},
{["loot_id"] = "22812", ["loot_name"] = "Nerubian Slavemaker", ["prio"] = " Prio: "},
{["loot_id"] = "22821", ["loot_name"] = "Doomfinger", ["prio"] = " Prio: "},
{["loot_id"] = "22819", ["loot_name"] = "Shield of Condemnation", ["prio"] = " Prio: "},
{["loot_id"] = "22802", ["loot_name"] = "Kingsfall", ["prio"] = " Prio: "},
{["loot_id"] = "23056", ["loot_name"] = "Hammer of the Twisting Nether", ["prio"] = " Prio: "},
{["loot_id"] = "23054", ["loot_name"] = "Gressil, Dawn of Ruin", ["prio"] = " Prio: "},
{["loot_id"] = "23577", ["loot_name"] = "The Hungering Cold", ["prio"] = " Prio: "},
{["loot_id"] = "22798", ["loot_name"] = "Might of Menethil", ["prio"] = " Prio: "},
{["loot_id"] = "22799", ["loot_name"] = "Soulseeker", ["prio"] = " Prio: "},
{["loot_id"] = "23060", ["loot_name"] = "Bonescythe Ring", ["prio"] = " Prio: "},
{["loot_id"] = "23066", ["loot_name"] = "Ring of Redemption", ["prio"] = " Prio: "},
{["loot_id"] = "23059", ["loot_name"] = "Ring of the Dreadnaught", ["prio"] = " Prio: "},
{["loot_id"] = "23062", ["loot_name"] = "Frostfire Ring", ["prio"] = " Prio: "},
{["loot_id"] = "23067", ["loot_name"] = "Ring of the Cryptstalker", ["prio"] = " Prio: "},
{["loot_id"] = "23061", ["loot_name"] = "Ring of Faith", ["prio"] = " Prio: "},
{["loot_id"] = "23063", ["loot_name"] = "Plagueheart Ring", ["prio"] = " Prio: "},
{["loot_id"] = "23064", ["loot_name"] = "Ring of the Dreamwalker", ["prio"] = " Prio: "},